### ISSUE TITLE
Requirements.txt

### ISSUE THREAD

**Issue by Starou** [Starou/SimpleIDML#1]
suds, lxml, ...

**Comment by memmott** [comment]
:+1: why not have one?

**Comment by Starou** [comment]
![the-reason](https://cloud.githubusercontent.com/assets/66106/14341583/3a68e276-fc93-11e5-8138-156450a743ec.png)

**Comment by Starou** [comment]
In fact we do not need a requirements.txt but a `install_requires` in setup.py.

http://python-packaging-user-guide.readthedocs.io/en/latest/requirements/#install-requires
