### ISSUE TITLE
`write` method inherited from zipfile fails (missing write mode)

### ISSUE THREAD

**Issue by riemannzetagambit** [Starou/SimpleIDML#16]
I'm trying to edit a template IDML package and populate it with some data that I generate based on some external parameters, and then save that to a new IDML file.

I have some code that looks like this, following some examples from the main repo page:

```python
report_package = idml.IDMLPackage('/path/to/my/template.idml')
with report_package.prefix("main") as f:
    [...some code that manipulates stories in the IDML...]
    f.write(filename)
```

This fails with the error `RuntimeError: write() requires mode "w" or "a"`. I am not sure have to pass the write mode to this method (I've tried some basic kwargs stuff in various places, e.g. `mode='w'`, to no effect). 

I can't really tell if I am editing the IDML template in the correct fashion, or if this is even how I should be saving it, but I don't think this behavior was intended.

Thanks ahead of time for any response.

**Comment by Starou** [comment]
The write mode is a parameter of `IDMLPackage` constructor (which is a subclass of [ZipFile](https://docs.python.org/2/library/zipfile.html#zipfile-objects)).

Like here: https://github.com/Starou/SimpleIDML/blob/master/src/simple_idml/decorators.py#L45

Below is a function that insert a IDML file (`module_filename`) into another one (`destination`). `insert_at` and `insert_only` being the XPath positions (where and what to insert).

```python
def insert_module(module_filename, prefix, destination, insert_at, insert_only,
                  debug=False, logger=None, logger_extra=None):
    # Inserted IDML needs to be prefixed and we don't want to lose the original so it is duplicated
    # in a working copy.
    module_tmp = NamedTemporaryFile()
    module_tmp.write(open(module_filename, mode="r").read())
    idml_package = idml.IDMLPackage(module_tmp)

    idml_package = idml_package.prefix(prefix)
    destination = destination.insert_idml(idml_package, at=insert_at, only=insert_only)
    idml_package.close()

    return destination
```

The magic happens here:

```python
 idml_package = idml_package.prefix(prefix)
```

And here:

```python
destination = destination.insert_idml(idml_package, at=insert_at, only=insert_only)
```

The IDMLPackage methods decorated with `@use_working_copy` return a «new» IDMLPackage that replace the original one (and so original packages like `idml_package` and `destination` don't need to be opened with the `mode="w"` flag).
If what you do does not fit in such methods, maybe you will find some inspiration in this decorator.

**Comment by riemannzetagambit** [comment]
Thanks for the response. I had tried opening with the mode as you specified, to wit `report_package = idml.IDMLPackage('/Users/dstone/reports/testing.idml', mode='w')` but this didn't seem to help me (it overwrote the IDML I was trying to edit). 

So no instead I am trying to use the inspiration you mentioned at the end-- I recognize now the side-effects of the methods in question vis a vis the `@use_working_copy` . To be more specific, my code is something like:

```python
report_package = idml.IDMLPackage('/path/to/my/template.idml')
story_ids = report_package.story_ids_for_node('/Root')
master_root = et.fromstring(report_package.xml_structure_pretty())

# CODE TO GET STORY XPATHS
story_xpaths = {}
tree = et.ElementTree(master_root)
for e in master_root.iter():
    story_id = e.attrib.get('XMLContent', None)
    if story_id in story_ids:
        story_xpaths[story_id] = tree.getpath(e)

# EDIT THE CONTENT OF EACH OF THE STORY XML FILES 
report_properties = ['name', 'address', 'item_ordered']

for story_id, story_xpath in story_xpaths.items():
    story = report_package.get_story_object_by_xpath(story_xpath)
    root = et.fromstring(story.tostring())

    for e in root.iter('XMLElement'):
        element_id = e.attrib['Self']
        report_property = e.attrib['MarkupTag'].split('/')[-1]

        if report_property in report_properties:
            # THIS LINE SHOULD EDIT THE IDMLPackage OBJECT IN PLACE
            story = story.set_element_content(element_id, new_report_property)
```
My understanding is that the last line should edit the IDMLPackage object and then I should be able to close the object and have a new IDML file with the new content in it. Is this the case?

I guess one question is if this is even the right method to approach my situation (this is now diverting from a github issue). I don't want to insert into my template IDML some other IDML; I just want to edit the underlying XML and save the edited IDML package to a new IDML file. Does that fit into the paradigm you mention above with the `insert_idml` method?

**Comment by Starou** [comment]
Hi,

This is the kind of manipulation that you can do without the need to go low-level (Etree etc) because the library can do all the tedious work for you. Use `SimpleIDML.stories` to works with `Story` files.

`Story` is a subclass of `components.IDMLXMLFile` and thus inherits of all the goodies.

Your 20 lines or so could be resumed by something like that:

```python
report_package = idml.IDMLPackage('/path/to/my/template.idml')
for story in report_package.stories:
    # Alter the story file here using methods provided.
    for id in ['name', 'address', 'item_ordered']:
        elt = story. get_element_by_id(id)
        ...
   # Save the story file.
    story.synchronize()
```

Maybe you don't even need to iterate on stories but just access the story using one of the `IDMLPackage.get_story_*` methods?

**Comment by riemannzetagambit** [comment]
Thanks again for responding. 

I don't think I can access the stories via `report_package.stories` because that returns a list of strings which are relative paths to the stories, not `Story` objects. I seem to only be able to access story objects via the `get_story_object_by_xpath` method, so that's why my janky code is the way it is.

I tried using the `story.synchronize()` call at the end of my code, which seemed to be the ticket. However, this raised an error because the internals want access to the `working_copy_path` property of the `Story` object, which seems to be inherited from the `IDMLPackage` class (see https://github.com/Starou/SimpleIDML/blob/master/src/simple_idml/idml.py#L27), which seems to default to `None`. I tried setting that property manually, but raised other errors in the process. I am trying to wrap my head around how this all interfaces with the `Zipfile` class and using the `with` clause as directed in your documentation, but I just don't seem to be able to make the darn thing work. Any advice here?

By the way, the specific error was 
```python
-----------------------
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-55-0e6db2f513f6> in <module>()
     33             if report_property in report_properties:
     34                 story.set_element_content(element_id, new_report_property)
---> 35                 story.synchronize()

/Users/dstone/.virtualenvs/trace_ve/lib/python2.7/site-packages/simple_idml/components.pyc in synchronize(self)
    107 
    108         # Must instanciate with a working_copy to use this.
--> 109         fobj = open(os.path.join(self.working_copy_path, self.name), mode="w+")
    110         fobj.write(self.tostring())
    111         fobj.close()

/Users/dstone/.virtualenvs/trace_ve/lib/python2.7/posixpath.pyc in join(a, *p)
     68         if b.startswith('/'):
     69             path = b
---> 70         elif path == '' or path.endswith('/'):
     71             path +=  b
     72         else:

AttributeError: 'NoneType' object has no attribute 'endswith'```

You can see it's erroring out because `story.working_copy_path` is `None` (and again, manually setting `story.working_copy_path=/path/to/my/template.idml`  yields another error, specifically `IOError: [Errno 2] No such file or directory...`).

Thanks again for your patience.

**Comment by Starou** [comment]
You are right about `stories()`, you may need to instantiate the objects yourself:

```python
for story_filename in report_package.stories:
    story = Story(report_package, story_filename, report_package.working_copy_path)
```

> _want access to the working_copy_path property of the Story object, which seems to be inherited from the IDMLPackage_

Well. Yes and no. This is not inherited. You have to explicitly pass the _working copy_ when you instantiate the _Story_, which is required to use `synchronize()` (as shown above).

Try to explicitly set this attribute on the IDMLPackage instance with something like that:

```python
report_package = idml.IDMLPackage('/path/to/my/template.idml')
tmp_filename = NamedTemporaryFile().name
report_package.extractall(tmp_filename)
report_package.working_copy_path = tmp_filename
```

**Comment by riemannzetagambit** [comment]
Since this issue was just closed, I just wanted to give a follow up on how we ended up solving this, for anyone who wants to do this in the future. 

For clarity, this was the scope of the problem we had: We want to generate automated reports for some content, and have an IDML template file that is marked up with tagged XML elements. I want to populate the IDML file with content identified by those XML tags in an automated fashion so I can send out (aesthetically beautiful, which is Adobe's job) reports in a timely manner.

To do this, we first created a template and imposed XML structure on it with hierarchical tags (don't think a hierarchy is necessary, though). You can add XML tags to frames, text, and other objects in an InDesign document in Adobe's software. We exported that document as an IDML file to be read by `SimpleIDML`.

Then, we had some code something like the following:
```python
from simple_idml import idml
from simple_idml.components import Story

report_package = idml.IDMLPackage('path/to/idml/template')
report_package.extractall(path='your/working/directory/path')
report_package.working_copy_path = 'your/working/directory/path'

# go through and edit the appropriate content of the IDML structure
with report_package.prefix('main') as f:
    for story_filename in f.stories:
        story = Story(f, story_filename, f.working_copy_path)
        root = et.fromstring(story.tostring())

        for e in root.iter('XMLElement'):
            element_id = e.attrib['Self']
            # you must specify XML tags in your IDML template so that you can read their tag names like so
            report_property = e.attrib['MarkupTag'].split('/')[-1]

            # we have a dictionary of content we want to write to the template whose keys correspond to the `report_property` (cleaned up XML tag names) above
            if report_property in report_dict.keys():
                story.set_element_content(element_id, report_dict[report_property])
                story.synchronize()
```
From here on out there is some clean up to be done to zip everything together, since the `report_package.extractall()` line extracted it all. I will leave the reader to figure out how to do that so it can be read by InDesign (Adobe's forums discuss how IDML is packaged as some tiered zip files).

Hope this helps to anyone looking in the future. Took us awhile to piece it all together.

**Comment by Starou** [comment]
For the reader:[ there is a function](https://github.com/Starou/SimpleIDML/blob/master/src/simple_idml/extras.py#L7) in `extras.py` to zip a directory into a IDML package :-)
