### ISSUE TITLE
cant print export_xml()

### ISSUE THREAD

**Issue by grossosavoy** [Starou/SimpleIDML#58]
Hey, i am sure u can help me here. For some reason i cant print my idml file to xml with the export_xml function. I keep getting a syntax error.

`from simple_idml import idml 
idml_file = idml.IDMLPackage("/users/dsavoy/Desktop/Datatool2.0/files/RAC_datasheet.idml")
print idml_file.export_xml()`

![image](https://user-images.githubusercontent.com/9535298/104561220-585ba580-5647-11eb-9740-2fd97ee1493c.png)

Thanks for ur help.

**Comment by Starou** [comment]
Hi,

I think you are using deprecated Python 2 syntax in a Python 3 environment.
`print "hello"` is not valid anymore. Use `print()` instead.
