### ISSUE TITLE
C# IDML library

### ISSUE THREAD

**Issue by mariuszhermansdorfer** [Starou/SimpleIDML#64]
Hey there,

first of all huge thanks to the community for creating and maintaining this library!

I've been searching for a C# equivalent and it seems there is not much out there. Before I dive head-first into creating a .Net IDML library, I wanted to understand how you approached creating SimpleIDML. Was it all manual code writing based on the formal specs, or is there any semi-automated approach you were able to leverage?

I'd appreciate a pointer in the right direction.

**Comment by Starou** [comment]
Hi @mariuszhermansdorfer,

It was Mostly done by reverse engineering the IDML files and using the Adobe documentation. And a lot of try/error.

Good luck.

**Comment by mariuszhermansdorfer** [comment]
That's what I was afraid of :)
Thanks a lot @Starou!
